#!/usr/bin/env bash
# setup nginx on server
sudo apt-get update
sudo apt-get install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service stop nginx
sudo service start nginx
