#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely
# and traps some signals
handle_kill()
{
	echo "I hate the kill command"
	rm /var/run/myscript.pid
	exit
}

handle_int()
{
	echo "Y U no love me?!"
}

handle_quit()
{
	rm /var/run/myscript.pid
	exit
}

remove_file()
{
	rm /var/run/myscript.pid
}

trap handle_kill SIGTERM
trap handle_int SIGINT
trap handle_quit SIGQUIT 

echo "$!" > /var/run/myscript.pid
while true
do
	echo "To infinity and beyond"
	sleep 2
done
	
