#!/usr/bin/env bash
# This script traps SIGTERM signal and claims to be invicible
shout() 
{
	echo "I am invincible!!!"
}

trap shout SIGTERM
while true
do
	echo "To infinity and beyond"
	sleep 2
done
