#!/usr/bin/env bash
# This script prints "Best School" 10 times using a while loop
# Prints "Hi" on 9th print
count=0

while [ "$count" -ne 10 ]
do
	if [ "$count" = 8 ]
	then
		echo "Hi"
	else
		echo "Best School"
	fi
	(( count = count + 1 ))
done
