#!/usr/bin/env bash
# This script prints "Best School" 10 times using a while loop
# Prints "Hi" on 9th print
count=1

while [ "$count" -lt 11 ]
do
	if [ "$count" = 9 ]
	then
		echo "Hi"
	else
		echo "Best School"
	fi
	(( count = count + 1 ))
done
