#!/usr/bin/env bash
# This script prints "Best School" 10 times using a while loop
# prints "bad luck" on 4th print and "good luck" on 8th
count=1

while [ "$count" -lt 11 ]
do
	if [ "$count" = 4 ]
	then
		echo "bad luck"
	elif [ "$count" = 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( count = count + 1 ))
done
