#!/usr/bin/env bash
# This script displays time for 12:59 in minutes

hour=0
minute=1
while [ "$hour" -le 12 ]
do
	echo "Hour: $hour"
	minute=1
	while [ "$minute" -lt 60 ]
	do
		echo "$minute"
		(( minute += 1 ))
	done
	(( hour += 1 ))
done
