#!/usr/bin/env bash
# change localhost resolve IP to 127.0.0.2 and facebook.com to 8.8.8.8
# create copy of hosts file
cp -f /etc/hosts ~/hosts.new

# make changes on new hosts file
sed "s/127.0.0.1/127.0.0.2/" ~/hosts.new

if [ "$(grep "facebook.com" ~/hosts.new )" == "facebook.com" ]
then
	sed "s/.+facebook.com/8.8.8.8\tfacebook.com/" ~/hosts.new
else
	printf "8.8.8.8\tfacebook.com\n" >> ~/hosts.new
fi

# replace hosts file with new hosts file
cp -f ~/hosts.new /etc/hosts
